upstream django_v1 {
    server web_django:8000;
}

upstream flask_v2 {
    server checkout_flask:5000;
}

server {
    listen 80;

    # Legacy API: monolito en Django
    location /api/v1/ {
        proxy_pass http://django_v1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Funcionalidad estrangulada: cotización checkout en Flask
    location /api/v2/checkout/quote {
        proxy_pass http://flask_v2;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Todo lo demás sigue en Django
    location / {
        proxy_pass http://django_v1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
