# Generated by Django 5.2.11 on 2026-03-10 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CERTIFICATE', 'Certificate issued'), ('BADGE', 'Badge earned'), ('ENROLLMENT', 'Enrollment confirmed'), ('COURSE_UPDATE', 'Course updated'), ('ORDER', 'Order update'), ('SYSTEM', 'System message')], default='SYSTEM', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['user', '-fecha'], name='core_notifi_user_id_cef8a3_idx'), models.Index(fields=['user', 'leida'], name='core_notifi_user_id_566a9f_idx')],
            },
        ),
    ]
