# Generated by Django 5.2.11 on 2026-02-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descuento_porcentaje', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de descuento (ej. 10.00 = 10%)', max_digits=5, null=True)),
                ('descuento_fijo', models.DecimalField(blank=True, decimal_places=2, help_text='Monto fijo a descontar', max_digits=10, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('usos_maximos', models.PositiveIntegerField(default=1)),
                ('usos_actuales', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('MONTO_FIJO', 'Monto fijo')], default='PORCENTAJE', max_length=20)),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
