# Generated by Django 5.2.11 on 2026-02-11 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_add_cart_and_order_certificaciones'),
        ('transactions', '0003_add_pago_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrdenCertificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('certificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_orden', to='catalog.certificacionindustria')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_certificacion', to='transactions.orden')),
            ],
            options={
                'verbose_name': 'Item orden (certificación)',
                'verbose_name_plural': 'Items orden (certificaciones)',
            },
        ),
        migrations.CreateModel(
            name='ItemCarritoCertificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_certificacion', to='transactions.carritocompras')),
                ('certificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_carrito', to='catalog.certificacionindustria')),
            ],
            options={
                'verbose_name': 'Item carrito (certificación)',
                'verbose_name_plural': 'Items carrito (certificaciones)',
                'unique_together': {('carrito', 'certificacion')},
            },
        ),
    ]
