# Generated by Django 5.2.11 on 2026-04-10 01:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_add_cart_and_order_certificaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='tipo',
            field=models.CharField(choices=[('PORCENTAJE', 'Percentage'), ('MONTO_FIJO', 'Fixed amount')], default='PORCENTAJE', max_length=20),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Active'), ('COMPLETADA', 'Completed'), ('CANCELADA', 'Cancelled')], default='ACTIVA', max_length=20),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pending'), ('CONFIRMADA', 'Confirmed'), ('CANCELADA', 'Cancelled')], default='CONFIRMADA', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pending'), ('COMPLETADO', 'Completed'), ('FALLIDO', 'Failed'), ('REEMBOLSADO', 'Refunded')], default='COMPLETADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('SIMULADO', 'Simulated'), ('TARJETA_SIMULADA', 'Card (simulated)')], default='SIMULADO', max_length=30),
        ),
        migrations.AddIndex(
            model_name='inscripcion',
            index=models.Index(fields=['user', 'estado'], name='tx_insc_user_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['user', 'estado'], name='tx_orden_user_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['fecha_creacion'], name='tx_orden_fecha_creacion_idx'),
        ),
    ]
