# Generated by Django 5.2.11 on 2026-02-09 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('duracion_minutos', models.PositiveIntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='catalog.curso')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['curso', 'orden'],
                'unique_together': {('curso', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('VIDEO', 'Video'), ('TEXTO', 'Texto'), ('QUIZ', 'Quiz'), ('PRACTICA', 'Práctica')], default='TEXTO', max_length=20)),
                ('contenido', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('duracion_minutos', models.PositiveIntegerField(default=0)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecciones', to='catalog.modulo')),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'ordering': ['modulo', 'orden'],
                'unique_together': {('modulo', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='ProgresoLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='catalog.leccion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_lecciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de lección',
                'verbose_name_plural': 'Progresos de lecciones',
                'unique_together': {('user', 'leccion')},
            },
        ),
    ]
