# Generated by Django 5.2.11 on 2026-02-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_calificacion_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='info_evaluacion',
            field=models.TextField(blank=True, help_text='Criterios de exámenes, trabajos prácticos y sistema de calificaciones.'),
        ),
    ]
