# Generated by Django 5.2.11 on 2026-02-09 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_info_evaluacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificacionIndustria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('descripcion', models.TextField(help_text='Descripción extensa de la certificación y qué incluye.')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='certificaciones_industria/')),
                ('imagen_url', models.URLField(blank=True, help_text='URL de imagen alusiva (si no se sube archivo).')),
                ('duracion_estimada_horas', models.PositiveIntegerField(default=40)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('curso', models.OneToOneField(blank=True, help_text='Curso que al comprarse da acceso a esta certificación.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificacion_industria', to='catalog.curso')),
            ],
            options={
                'verbose_name': 'Certificación de industria',
                'verbose_name_plural': 'Certificaciones de industria',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ExamenCertificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('instrucciones', models.TextField(blank=True)),
                ('puntaje_minimo_aprobacion', models.PositiveSmallIntegerField(default=70, help_text='Porcentaje mínimo para aprobar (0-100).')),
                ('certificacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen', to='catalog.certificacionindustria')),
            ],
            options={
                'verbose_name': 'Examen de certificación',
                'verbose_name_plural': 'Exámenes de certificación',
            },
        ),
        migrations.CreateModel(
            name='PreguntaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='catalog.examencertificacion')),
            ],
            options={
                'ordering': ['examen', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='OpcionPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('es_correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='catalog.preguntaexamen')),
            ],
            options={
                'verbose_name': 'Opción de pregunta',
                'verbose_name_plural': 'Opciones de pregunta',
            },
        ),
        migrations.CreateModel(
            name='SeccionMaterialCertificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('contenido', models.TextField(help_text='Contenido en texto o HTML.')),
                ('certificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones_material', to='catalog.certificacionindustria')),
            ],
            options={
                'ordering': ['certificacion', 'orden'],
                'unique_together': {('certificacion', 'orden')},
            },
        ),
    ]
