# Generated by Django 5.2.11 on 2026-02-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_add_certificacion_industria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificacionindustria',
            name='curso',
        ),
    ]
