# Generated by Django 5.2.11 on 2026-02-09 19:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_curso_from_certificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificacionindustria',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Precio para acceder al material y al examen (pago simulado).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='certificacionindustria',
            name='descripcion',
            field=models.TextField(help_text='Descripción extensa: qué avala, a quién va dirigida, qué incluye.'),
        ),
        migrations.CreateModel(
            name='AccesoCertificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('certificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='catalog.certificacionindustria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_certificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_compra'],
                'unique_together': {('user', 'certificacion')},
            },
        ),
        migrations.CreateModel(
            name='DiplomaCertificacionIndustria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_examen', models.DateTimeField(auto_now_add=True)),
                ('puntaje', models.PositiveSmallIntegerField(help_text='Porcentaje obtenido (0-100).')),
                ('aprobado', models.BooleanField(default=True)),
                ('codigo_verificacion', models.CharField(max_length=24, unique=True)),
                ('certificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='catalog.certificacionindustria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas_certificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_examen'],
                'unique_together': {('user', 'certificacion')},
            },
        ),
    ]
