# Generated by Django 5.2.11 on 2026-02-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_add_precio_acceso_diploma_certificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel_dificultad',
            field=models.CharField(choices=[('PRINCIPIANTE', 'Beginner'), ('INTERMEDIO', 'Intermediate'), ('AVANZADO', 'Advanced'), ('EXPERTO', 'Expert')], default='PRINCIPIANTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='leccion',
            name='tipo',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('TEXTO', 'Text'), ('QUIZ', 'Quiz'), ('PRACTICA', 'Practice')], default='TEXTO', max_length=20),
        ),
    ]
