# Generated by Django 5.2.11 on 2026-03-10 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_add_cart_and_order_certificaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Draft'), ('EN_REVISION', 'In review'), ('PUBLICADO', 'Published'), ('PAUSADO', 'Paused'), ('ARCHIVADO', 'Archived')], default='BORRADOR', max_length=20),
        ),
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FIRST_COURSE', 'First Steps'), ('THREE_COURSES', 'Rising Star'), ('FIVE_COURSES', 'Master Learner'), ('TEN_COURSES', 'Unstoppable'), ('FIRST_REVIEW', 'First Review'), ('FIVE_REVIEWS', 'Top Critic'), ('INDUSTRY_CERT', 'Industry Pro'), ('PERFECT_SCORE', 'Perfect Score')], max_length=30)),
                ('fecha_obtencion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insignias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insignia',
                'verbose_name_plural': 'Insignias',
                'ordering': ['-fecha_obtencion'],
                'unique_together': {('user', 'tipo')},
            },
        ),
    ]
