# Generated by Django 5.2.11 on 2026-04-10 01:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_add_wishlist_and_notifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='catalog_curso_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['categoria', 'estado'], name='catalog_curso_cat_estado_idx'),
        ),
    ]
