"""add trayectorias

Revision ID: 1f31b592b886
Revises: 6bb3469bea64
Create Date: 2026-06-12 21:03:56.647229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f31b592b886'
down_revision: Union[str, Sequence[str], None] = '6bb3469bea64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trayectorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria_general', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trayectorias_id'), 'trayectorias', ['id'], unique=False)
    op.create_table('trayectoria_cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trayectoria_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['trayectoria_id'], ['trayectorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trayectoria_cursos_course_id'), 'trayectoria_cursos', ['course_id'], unique=False)
    op.create_index(op.f('ix_trayectoria_cursos_id'), 'trayectoria_cursos', ['id'], unique=False)
    op.create_index(op.f('ix_trayectoria_cursos_trayectoria_id'), 'trayectoria_cursos', ['trayectoria_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trayectoria_cursos_trayectoria_id'), table_name='trayectoria_cursos')
    op.drop_index(op.f('ix_trayectoria_cursos_id'), table_name='trayectoria_cursos')
    op.drop_index(op.f('ix_trayectoria_cursos_course_id'), table_name='trayectoria_cursos')
    op.drop_table('trayectoria_cursos')
    op.drop_index(op.f('ix_trayectorias_id'), table_name='trayectorias')
    op.drop_table('trayectorias')
    # ### end Alembic commands ###
