"""add certificacion fields

Revision ID: 3445a63f1139
Revises: 69d2bafa964d
Create Date: 2026-06-13 01:35:33.494993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3445a63f1139'
down_revision: Union[str, Sequence[str], None] = '69d2bafa964d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('es_certificacion', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('modules', sa.Column('es_examen_modulo', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('modules', sa.Column('es_examen_final', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'es_examen_final')
    op.drop_column('modules', 'es_examen_modulo')
    op.drop_column('courses', 'es_certificacion')
    # ### end Alembic commands ###
