"""add imagen_url to courses and trayectorias

Revision ID: ed10a10f5f8f
Revises: 3445a63f1139
Create Date: 2026-06-13 16:54:59.749956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed10a10f5f8f'
down_revision: Union[str, Sequence[str], None] = '3445a63f1139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('imagen_url', sa.String(length=500), nullable=True))
    op.add_column('trayectorias', sa.Column('imagen_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trayectorias', 'imagen_url')
    op.drop_column('courses', 'imagen_url')
    # ### end Alembic commands ###
